GET http://localhost:8080/api/companies

###
GET http://localhost:8080/api/companies/67b47153b03ab21750f5aadd

###
POST http://localhost:8080/api/companies HTTP/1.1
content-type: application/json

{
    "name": "Delta",
    "size": 180
}

###
DELETE http://localhost:8080/api/companies/67b3b32f3da84feb7278cca7